name: Publish on MarketPlace

on:
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Build and publish on VSCode Marketplace
      run: |
        npm install
        npm i -g vsce
        vsce package
        vsce publish -p ${{ secrets.MARKETPLACE_TOKEN }}
    - name: Build and publish on Open VSX Registry
      run: |
        npm install
        npm i -g ovsx
        npx ovsx publish -p ${{ secrets.OPEN_VSX_TOKEN }}
      env:
        CI: true
